! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_JacobianSP.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(61) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  5, &
       6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8, &
       8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, &
      10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, &
      12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, &
      13 /)

  INTEGER, PARAMETER, DIMENSION(61) :: LU_ICOL = (/ &
       1, 11, 13,  2,  9,  3, 13,  4, 11,  5,  8, 13, &
       3,  6, 12, 13,  7,  9, 10, 12,  5,  8,  9, 11, &
      12, 13,  9, 10, 11, 12,  4,  8,  9, 10, 11, 12, &
      13,  4,  7,  9, 10, 11, 12, 13,  6,  7,  8,  9, &
      10, 11, 12, 13,  5,  6,  7,  8,  9, 10, 11, 12, &
      13 /)

  INTEGER, PARAMETER, DIMENSION(14) :: LU_CROW = (/ &
       1,  4,  6,  8, 10, 13, 17, 21, 27, 31, 38, 45, &
      53, 62 /)

  INTEGER, PARAMETER, DIMENSION(14) :: LU_DIAG = (/ &
       1,  4,  6,  8, 10, 14, 17, 22, 27, 34, 42, 51, &
      61, 62 /)


END MODULE kchem_kpp_JacobianSP

