! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_HessianSP.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_I = (/ &
       1,  4,  5,  6,  7,  7,  8,  8,  8,  9,  9, 10, &
      10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, &
      13, 13, 13, 13 /)

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_J = (/ &
      11,  4,  8,  6,  7, 10,  8,  8,  9,  9, 10,  4, &
       8, 10,  4,  7,  9, 11,  6,  7,  8, 10,  6,  7, &
       8,  8, 10, 11 /)

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_K = (/ &
      13, 11, 13, 12, 12, 12, 12, 13, 11, 11, 12, 11, &
      12, 12, 11, 12, 11, 13, 12, 12, 12, 12, 12, 12, &
      12, 13, 12, 13 /)


END MODULE kchem_kpp_HessianSP

