! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_Parameters.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_Parameters

  USE kchem_kpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 16 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 13 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 11 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 3 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 12 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 14 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 55 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 61 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 14 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 13 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 28 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_HNO3 = 1 
  INTEGER, PARAMETER :: ind_CO = 2 
  INTEGER, PARAMETER :: ind_O = 3 
  INTEGER, PARAMETER :: ind_RH = 4 
  INTEGER, PARAMETER :: ind_RCOO2NO2 = 5 
  INTEGER, PARAMETER :: ind_O3 = 6 
  INTEGER, PARAMETER :: ind_HO2 = 7 
  INTEGER, PARAMETER :: ind_RCOO2 = 8 
  INTEGER, PARAMETER :: ind_RCHO = 9 
  INTEGER, PARAMETER :: ind_RO2 = 10 
  INTEGER, PARAMETER :: ind_OH = 11 
  INTEGER, PARAMETER :: ind_NO = 12 
  INTEGER, PARAMETER :: ind_NO2 = 13 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 14 
  INTEGER, PARAMETER :: ind_O2 = 15 
  INTEGER, PARAMETER :: ind_CO2 = 16 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_CO2 = 3 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 20 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 40 

END MODULE kchem_kpp_Parameters

