! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_Function.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_Function

  USE kchem_kpp_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(13)
  A(2) = RCT(2)*V(3)*F(2)
  A(3) = RCT(3)*V(6)*V(12)
  A(4) = RCT(4)*V(4)*V(11)
  A(5) = RCT(5)*V(9)*V(11)
  A(6) = RCT(6)*V(9)
  A(7) = RCT(7)*V(7)*V(12)
  A(8) = RCT(8)*V(10)*V(12)
  A(9) = RCT(9)*V(8)*V(12)
  A(10) = RCT(10)*V(11)*V(13)
  A(11) = RCT(11)*V(8)*V(13)
  A(12) = RCT(12)*V(5)

! Aggregate function
  Vdot(1) = A(10)
  Vdot(2) = A(6)
  Vdot(3) = A(1)-A(2)
  Vdot(4) = -A(4)
  Vdot(5) = A(11)-A(12)
  Vdot(6) = A(2)-A(3)
  Vdot(7) = A(6)-A(7)+A(8)
  Vdot(8) = A(5)-A(9)-A(11)+A(12)
  Vdot(9) = -A(5)-A(6)+A(8)
  Vdot(10) = A(4)+A(6)-A(8)+A(9)
  Vdot(11) = -A(4)-A(5)+A(7)-A(10)
  Vdot(12) = A(1)-A(3)-A(7)-A(8)-A(9)
  Vdot(13) = -A(1)+A(3)+A(7)+A(8)+A(9)-A(10)-A(11)+A(12)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE kchem_kpp_Function

