! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_Jacobian.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_Jacobian

  USE kchem_kpp_Parameters
  USE kchem_kpp_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(21)

! B(1) = dA(1)/dV(13)
  B(1) = RCT(1)
! B(2) = dA(2)/dV(3)
  B(2) = RCT(2)*F(2)
! B(4) = dA(3)/dV(6)
  B(4) = RCT(3)*V(12)
! B(5) = dA(3)/dV(12)
  B(5) = RCT(3)*V(6)
! B(6) = dA(4)/dV(4)
  B(6) = RCT(4)*V(11)
! B(7) = dA(4)/dV(11)
  B(7) = RCT(4)*V(4)
! B(8) = dA(5)/dV(9)
  B(8) = RCT(5)*V(11)
! B(9) = dA(5)/dV(11)
  B(9) = RCT(5)*V(9)
! B(10) = dA(6)/dV(9)
  B(10) = RCT(6)
! B(11) = dA(7)/dV(7)
  B(11) = RCT(7)*V(12)
! B(12) = dA(7)/dV(12)
  B(12) = RCT(7)*V(7)
! B(13) = dA(8)/dV(10)
  B(13) = RCT(8)*V(12)
! B(14) = dA(8)/dV(12)
  B(14) = RCT(8)*V(10)
! B(15) = dA(9)/dV(8)
  B(15) = RCT(9)*V(12)
! B(16) = dA(9)/dV(12)
  B(16) = RCT(9)*V(8)
! B(17) = dA(10)/dV(11)
  B(17) = RCT(10)*V(13)
! B(18) = dA(10)/dV(13)
  B(18) = RCT(10)*V(11)
! B(19) = dA(11)/dV(8)
  B(19) = RCT(11)*V(13)
! B(20) = dA(11)/dV(13)
  B(20) = RCT(11)*V(8)
! B(21) = dA(12)/dV(5)
  B(21) = RCT(12)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,11)
  JVS(2) = B(17)
! JVS(3) = Jac_FULL(1,13)
  JVS(3) = B(18)
! JVS(4) = Jac_FULL(2,2)
  JVS(4) = 0
! JVS(5) = Jac_FULL(2,9)
  JVS(5) = B(10)
! JVS(6) = Jac_FULL(3,3)
  JVS(6) = -B(2)
! JVS(7) = Jac_FULL(3,13)
  JVS(7) = B(1)
! JVS(8) = Jac_FULL(4,4)
  JVS(8) = -B(6)
! JVS(9) = Jac_FULL(4,11)
  JVS(9) = -B(7)
! JVS(10) = Jac_FULL(5,5)
  JVS(10) = -B(21)
! JVS(11) = Jac_FULL(5,8)
  JVS(11) = B(19)
! JVS(12) = Jac_FULL(5,13)
  JVS(12) = B(20)
! JVS(13) = Jac_FULL(6,3)
  JVS(13) = B(2)
! JVS(14) = Jac_FULL(6,6)
  JVS(14) = -B(4)
! JVS(15) = Jac_FULL(6,12)
  JVS(15) = -B(5)
! JVS(16) = Jac_FULL(6,13)
  JVS(16) = 0
! JVS(17) = Jac_FULL(7,7)
  JVS(17) = -B(11)
! JVS(18) = Jac_FULL(7,9)
  JVS(18) = B(10)
! JVS(19) = Jac_FULL(7,10)
  JVS(19) = B(13)
! JVS(20) = Jac_FULL(7,12)
  JVS(20) = -B(12)+B(14)
! JVS(21) = Jac_FULL(8,5)
  JVS(21) = B(21)
! JVS(22) = Jac_FULL(8,8)
  JVS(22) = -B(15)-B(19)
! JVS(23) = Jac_FULL(8,9)
  JVS(23) = B(8)
! JVS(24) = Jac_FULL(8,11)
  JVS(24) = B(9)
! JVS(25) = Jac_FULL(8,12)
  JVS(25) = -B(16)
! JVS(26) = Jac_FULL(8,13)
  JVS(26) = -B(20)
! JVS(27) = Jac_FULL(9,9)
  JVS(27) = -B(8)-B(10)
! JVS(28) = Jac_FULL(9,10)
  JVS(28) = B(13)
! JVS(29) = Jac_FULL(9,11)
  JVS(29) = -B(9)
! JVS(30) = Jac_FULL(9,12)
  JVS(30) = B(14)
! JVS(31) = Jac_FULL(10,4)
  JVS(31) = B(6)
! JVS(32) = Jac_FULL(10,8)
  JVS(32) = B(15)
! JVS(33) = Jac_FULL(10,9)
  JVS(33) = B(10)
! JVS(34) = Jac_FULL(10,10)
  JVS(34) = -B(13)
! JVS(35) = Jac_FULL(10,11)
  JVS(35) = B(7)
! JVS(36) = Jac_FULL(10,12)
  JVS(36) = -B(14)+B(16)
! JVS(37) = Jac_FULL(10,13)
  JVS(37) = 0
! JVS(38) = Jac_FULL(11,4)
  JVS(38) = -B(6)
! JVS(39) = Jac_FULL(11,7)
  JVS(39) = B(11)
! JVS(40) = Jac_FULL(11,9)
  JVS(40) = -B(8)
! JVS(41) = Jac_FULL(11,10)
  JVS(41) = 0
! JVS(42) = Jac_FULL(11,11)
  JVS(42) = -B(7)-B(9)-B(17)
! JVS(43) = Jac_FULL(11,12)
  JVS(43) = B(12)
! JVS(44) = Jac_FULL(11,13)
  JVS(44) = -B(18)
! JVS(45) = Jac_FULL(12,6)
  JVS(45) = -B(4)
! JVS(46) = Jac_FULL(12,7)
  JVS(46) = -B(11)
! JVS(47) = Jac_FULL(12,8)
  JVS(47) = -B(15)
! JVS(48) = Jac_FULL(12,9)
  JVS(48) = 0
! JVS(49) = Jac_FULL(12,10)
  JVS(49) = -B(13)
! JVS(50) = Jac_FULL(12,11)
  JVS(50) = 0
! JVS(51) = Jac_FULL(12,12)
  JVS(51) = -B(5)-B(12)-B(14)-B(16)
! JVS(52) = Jac_FULL(12,13)
  JVS(52) = B(1)
! JVS(53) = Jac_FULL(13,5)
  JVS(53) = B(21)
! JVS(54) = Jac_FULL(13,6)
  JVS(54) = B(4)
! JVS(55) = Jac_FULL(13,7)
  JVS(55) = B(11)
! JVS(56) = Jac_FULL(13,8)
  JVS(56) = B(15)-B(19)
! JVS(57) = Jac_FULL(13,9)
  JVS(57) = 0
! JVS(58) = Jac_FULL(13,10)
  JVS(58) = B(13)
! JVS(59) = Jac_FULL(13,11)
  JVS(59) = -B(17)
! JVS(60) = Jac_FULL(13,12)
  JVS(60) = B(5)+B(12)+B(14)+B(16)
! JVS(61) = Jac_FULL(13,13)
  JVS(61) = -B(1)-B(18)-B(20)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(11)+JVS(3)*UV(13)
  JUV(2) = JVS(4)*UV(2)+JVS(5)*UV(9)
  JUV(3) = JVS(6)*UV(3)+JVS(7)*UV(13)
  JUV(4) = JVS(8)*UV(4)+JVS(9)*UV(11)
  JUV(5) = JVS(10)*UV(5)+JVS(11)*UV(8)+JVS(12)*UV(13)
  JUV(6) = JVS(13)*UV(3)+JVS(14)*UV(6)+JVS(15)*UV(12)
  JUV(7) = JVS(17)*UV(7)+JVS(18)*UV(9)+JVS(19)*UV(10)+JVS(20)*UV(12)
  JUV(8) = JVS(21)*UV(5)+JVS(22)*UV(8)+JVS(23)*UV(9)+JVS(24)*UV(11)+JVS(25)*UV(12)+JVS(26)*UV(13)
  JUV(9) = JVS(27)*UV(9)+JVS(28)*UV(10)+JVS(29)*UV(11)+JVS(30)*UV(12)
  JUV(10) = JVS(31)*UV(4)+JVS(32)*UV(8)+JVS(33)*UV(9)+JVS(34)*UV(10)+JVS(35)*UV(11)+JVS(36)*UV(12)
  JUV(11) = JVS(38)*UV(4)+JVS(39)*UV(7)+JVS(40)*UV(9)+JVS(42)*UV(11)+JVS(43)*UV(12)+JVS(44)*UV(13)
  JUV(12) = JVS(45)*UV(6)+JVS(46)*UV(7)+JVS(47)*UV(8)+JVS(49)*UV(10)+JVS(51)*UV(12)+JVS(52)*UV(13)
  JUV(13) = JVS(53)*UV(5)+JVS(54)*UV(6)+JVS(55)*UV(7)+JVS(56)*UV(8)+JVS(58)*UV(10)+JVS(59)*UV(11)+JVS(60)*UV(12)+JVS(61)&
              &*UV(13)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(4)*UV(2)
  JTUV(3) = JVS(6)*UV(3)+JVS(13)*UV(6)
  JTUV(4) = JVS(8)*UV(4)+JVS(31)*UV(10)+JVS(38)*UV(11)
  JTUV(5) = JVS(10)*UV(5)+JVS(21)*UV(8)+JVS(53)*UV(13)
  JTUV(6) = JVS(14)*UV(6)+JVS(45)*UV(12)+JVS(54)*UV(13)
  JTUV(7) = JVS(17)*UV(7)+JVS(39)*UV(11)+JVS(46)*UV(12)+JVS(55)*UV(13)
  JTUV(8) = JVS(11)*UV(5)+JVS(22)*UV(8)+JVS(32)*UV(10)+JVS(47)*UV(12)+JVS(56)*UV(13)
  JTUV(9) = JVS(5)*UV(2)+JVS(18)*UV(7)+JVS(23)*UV(8)+JVS(27)*UV(9)+JVS(33)*UV(10)+JVS(40)*UV(11)
  JTUV(10) = JVS(19)*UV(7)+JVS(28)*UV(9)+JVS(34)*UV(10)+JVS(49)*UV(12)+JVS(58)*UV(13)
  JTUV(11) = JVS(2)*UV(1)+JVS(9)*UV(4)+JVS(24)*UV(8)+JVS(29)*UV(9)+JVS(35)*UV(10)+JVS(42)*UV(11)+JVS(59)*UV(13)
  JTUV(12) = JVS(15)*UV(6)+JVS(20)*UV(7)+JVS(25)*UV(8)+JVS(30)*UV(9)+JVS(36)*UV(10)+JVS(43)*UV(11)+JVS(51)*UV(12)&
               &+JVS(60)*UV(13)
  JTUV(13) = JVS(3)*UV(1)+JVS(7)*UV(3)+JVS(12)*UV(5)+JVS(26)*UV(8)+JVS(44)*UV(11)+JVS(52)*UV(12)+JVS(61)*UV(13)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE kchem_kpp_Jacobian

