! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kchem_kpp_Monitor.f90
! Time                 : Thu Sep  7 11:39:19 2017
! Working directory    : /pd/home/khan-b/github/palm-4u/current_version/trunk/KPP_FOR_PALM/tmp_kp4
! Equation file        : kchem_kpp.kpp
! Output root filename : kchem_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kchem_kpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(16) :: SPC_NAMES = (/ &
     'HNO3           ','CO             ','O              ', &
     'RH             ','RCOO2NO2       ','O3             ', &
     'HO2            ','RCOO2          ','RCHO           ', &
     'RO2            ','OH             ','NO             ', &
     'NO2            ','H2O            ','O2             ', &
     'CO2            ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(12) :: EQN_NAMES = (/ &
     '        NO2 --> O + NO                                                                              ', &
     '     O + O2 --> O3                                                                                  ', &
     '    O3 + NO --> NO2 + O2                                                                            ', &
     '    RH + OH --> RO2 + H2O                                                                           ', &
     '  RCHO + OH --> RCOO2 + H2O                                                                         ', &
     '       RCHO --> CO + HO2 + RO2                                                                      ', &
     '   HO2 + NO --> OH + NO2                                                                            ', &
     '   RO2 + NO --> HO2 + RCHO + NO2                                                                    ', &
     ' RCOO2 + NO --> RO2 + NO2 + CO2                                                                     ', &
     '   OH + NO2 --> HNO3                                                                                ', &
     'RCOO2 + NO2 --> RCOO2NO2                                                                            ', &
     '   RCOO2NO2 --> RCOO2 + NO2                                                                         ' /)

! INLINED global variables

  !   Declaration of global variables for photolysis from INLINE
  INTEGER, PARAMETER :: NPHOT = 2
  !   phot Photolysis frequencies 
  REAL(kind=dp) :: phot(NPHOT)

  INTEGER, PARAMETER,PUBLIC :: j_NO2 = 1
  INTEGER, PARAMETER,PUBLIC :: j_rcho = 2

  CHARACTER(LEN=15), PARAMETER, DIMENSION(NPHOT) :: PHOT_NAMES =  (/ &
     'J_NO2          ','J_RCHO         '/)

! End INLINED global variables


END MODULE kchem_kpp_Monitor
